# Generated by Django 4.1 on 2022-08-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Pon nombre del director', max_length=32)),
                ('apellido', models.CharField(help_text='Pon apellido del director', max_length=32)),
                ('brithday', models.DateField(help_text='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Pon el nombre de la pelicula', max_length=32)),
                ('fecha_de_estreno', models.DateTimeField(help_text='Fecha de estreno')),
                ('summary', models.TextField(help_text='Pon un resumen', max_length=100)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directors.director')),
            ],
        ),
    ]
